"""add_quiz_type_and_deadline

Revision ID: 0a416fb4626a
Revises: a1b2c3d4e5f6
Create Date: 2026-03-11 16:59:50.363458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a416fb4626a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('quiz_type', sa.String(length=20), server_default='self_paced', nullable=False))
    op.add_column('quizzes', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'deadline')
    op.drop_column('quizzes', 'quiz_type')
    # ### end Alembic commands ###
