"""add_last_risk_label_to_users

Revision ID: 0e59b3d0c3ae
Revises: 5470752a5220
Create Date: 2026-03-04 11:03:53.352457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e59b3d0c3ae'
down_revision: Union[str, None] = '5470752a5220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_risk_label', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_risk_label')
    # ### end Alembic commands ###
